version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: cron
      cronjob: 0 6 * * *
      timezone: America/Los_Angeles
    cooldown:
      default-days: 14
    groups:
      actions:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: cron
      cronjob: 0 6 * * *
      timezone: America/Los_Angeles
    allow:
      - dependency-type: direct
    cooldown:
      default-days: 14
    groups:
      dependencies:
        applies-to: version-updates
        patterns:
          - "*"
